### ISSUE TITLE
Incorrect use of `assume_init`

### ISSUE THREAD

**Issue by RalfJung** [ntex-rs/ntex#106]
By coincidence, I noticed this code in your crate:
https://github.com/ntex-rs/ntex/blob/fb6c16fcb2c9f9f48abfc264d63b4641251f30de/ntex-bytes/src/bytes.rs#L2965-L2966

This violates the [safety condition of `assume_init`](https://doc.rust-lang.org/nightly/std/mem/union.MaybeUninit.html#method.assume_init): it is not correct to call `assume_init` until all the fields have actually been initialized. (That's also why lints warn strongly against doing that. This is the same level of "wrong" as C code that causes a signed integer overflow.) This can probably be fixed by keeping `inner` at type `MaybeUninit<inner>` and calling `inner.assume_init()` only at the very end, when the function returns.

**Comment by fafhrd91** [comment]
uninit memory is never used, implementation control this invariant.


btw is this issue created by bot?

**Comment by RalfJung** [comment]
No I'm a person. :) I am a leader of the [Unsafe Code Guidelines WG](https://github.com/rust-lang/unsafe-code-guidelines/).
A bot (but not mine) found this bug but I verified it before creating the issue.

> uninit memory is never used, implementation control this invariant.

It doesn't matter whether the memory is used or not. Please read [the `assume_init` documentation](https://doc.rust-lang.org/nightly/std/mem/union.MaybeUninit.html#method.assume_init).
You can easily check that this code has UB by testing it with [Miri](https://github.com/rust-lang/miri). If you run [this code](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=3c86550e07dda3f122b0c0f3af1f9ad5) (click " Tools - Miri") it will print
```
error: Undefined Behavior: type validation failed at .value.arc.pointer: encountered uninitialized raw pointer
  [--> src/main.rs:14:34
](https://play.rust-lang.org/#)   |
14 |     let _inner: Inner = unsafe { mem::MaybeUninit::uninit().assume_init() };
   |                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ type validation failed at .value.arc.pointer: encountered uninitialized raw pointer
   |
   = help: this indicates a bug in the program: it performed an invalid operation, and caused Undefined Behavior
   = help: see https://doc.rust-lang.org/nightly/reference/behavior-considered-undefined.html for further information
```

**Comment by RalfJung** [comment]
Also note the lint being printed:
```
warning: the type `Inner` does not permit being left uninitialized
  [--> src/main.rs:14:34
](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=3c86550e07dda3f122b0c0f3af1f9ad5#)   |
14 |     let _inner: Inner = unsafe { mem::MaybeUninit::uninit().assume_init() };
   |                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |                                  |
   |                                  this code causes undefined behavior when executed
   |                                  help: use `MaybeUninit<T>` instead, and only call `assume_init` after initialization is done
   |
   = note: `#[warn(invalid_value)]` on by default
note: `std::ptr::NonNull<Shared>` must be non-null (in this struct field)
  [--> src/main.rs:7:5
](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=3c86550e07dda3f122b0c0f3af1f9ad5#)   |
7  |     arc: NonNull<Shared>,
   |     ^^^^^^^^^^^^^^^^^^^^
```
Nowhere does it say there is an exception for when the uninit memory is "not used", or anything like that. "this code causes undefined behavior when executed", under all conditions.

If you want to learn more about why data needs to be valid even when it is "unused", I [wrote a blog post on that subject](https://www.ralfj.de/blog/2020/07/15/unused-data.html).

**Comment by xspio** [comment]
@RalfJung Are you serious? I wish you were a bot.

**Comment by fakeshadow** [comment]
> Also note the lint being printed:
> 
> ```
> warning: the type `Inner` does not permit being left uninitialized
>   [--> src/main.rs:14:34
> ](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=3c86550e07dda3f122b0c0f3af1f9ad5#)   |
> 14 |     let _inner: Inner = unsafe { mem::MaybeUninit::uninit().assume_init() };
>    |                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>    |                                  |
>    |                                  this code causes undefined behavior when executed
>    |                                  help: use `MaybeUninit<T>` instead, and only call `assume_init` after initialization is done
>    |
>    = note: `#[warn(invalid_value)]` on by default
> note: `std::ptr::NonNull<Shared>` must be non-null (in this struct field)
>   [--> src/main.rs:7:5
> ](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=3c86550e07dda3f122b0c0f3af1f9ad5#)   |
> 7  |     arc: NonNull<Shared>,
>    |     ^^^^^^^^^^^^^^^^^^^^
> ```
> 
> Nowhere does it say there is an exception for when the uninit memory is "not used", or anything like that. "this code causes undefined behavior when executed", under all conditions.
> 
> If you want to learn more about why data needs to be valid even when it is "unused", I [wrote a blog post on that subject](https://www.ralfj.de/blog/2020/07/15/unused-data.html).

What about this? Does partial inintialization with transmute cause ub?
```rust
let mut arr: [MaybeUninit<u8>; 8] = unsafe { MaybeUninit::uninit().assume_init() };
arr[0].write(1);
arr[1].write(2);
let slice: &[u8] = unsafe { mem::transmute(&arr[..2]) };
```

**Comment by RalfJung** [comment]
> What about this? Does partial inintialization with transmute cause ub?

As long as you only `transmute` initialized parts, you are fine. But you can avoid `transmute` by using [slice_assume_init_mut](https://doc.rust-lang.org/nightly/core/mem/union.MaybeUninit.html#method.slice_assume_init_mut) instead.

> @RalfJung Are you serious? I wish you were a bot.

Wow. You might want to overthink how you interact with other people on the internet.
I am unsubscribing form this thread.

**Comment by fakeshadow** [comment]
> As long as you only `transmute` initialized parts, you are fine. But you can avoid `transmute` by using [slice_assume_init_mut](https://doc.rust-lang.org/nightly/core/mem/union.MaybeUninit.html#method.slice_assume_init_mut) instead.

Thanks for the answer. I looked at said api and indeed pointer casting is better.

**Comment by botika** [comment]
@RalfJung Seriously, dedicate yourselves to making software and stop bothering those who have the detail to offer us something as good as ntex.

**Comment by RalfJung** [comment]
`ntex` has a critical bug. (I should note that the `bytes` crate this code is forked from is fine; the bug was introduced in the ntex fork or was fixed upstream in the mean time.) I told you guys about it because I care deeply about making unsafe Rust as reliable as possible (e.g. by writing and maintaining tools like [Miri](https://github.com/rust-lang/miri/), which can help you to find bugs like this). It's entirely up to you what you want to do about that. You can be angry at the messenger or try to fix the problem.

Please don't ping me again.

**Comment by fakeshadow** [comment]
> `ntex` has a critical bug. (I should note that the `bytes` crate this code is forked from is fine; the bug was introduced in the ntex fork or was fixed upstream in the mean time.) I told you guys about it because I care deeply about making unsafe Rust as reliable as possible (e.g. by writing and maintaining tools like [Miri](https://github.com/rust-lang/miri/), which can help you to find bugs like this). It's entirely up to you what you want to do about that. You can be angry at the messenger or try to fix the problem.
> 
> Please don't ping me again.

I appreciate your effort. It's sad the community can be toxic at times.

**Comment by fafhrd91** [comment]
I am not sure how to fix this code, and [bytes](https://github.com/tokio-rs/bytes/blob/d43e283e5ed520e54df2428f2cf9a7c13c79ff49/src/bytes.rs#L1824) is not fixed as well.

**Comment by fafhrd91** [comment]
> `ntex` has a critical bug. (I should note that the `bytes` crate this code is forked from is fine; the bug was introduced in the ntex fork or was fixed upstream in the mean time.) I told you guys about it because I care deeply about making unsafe Rust as reliable as possible (e.g. by writing and maintaining tools like [Miri](https://github.com/rust-lang/miri/), which can help you to find bugs like this). It's entirely up to you what you want to do about that. You can be angry at the messenger or try to fix the problem.

I think main reason why some people are "angry at the messenger" is that this issue is created outside of feature context, just with reliance on output of Miri. This seems common for rust community, context does not matter, formal compliance with the tooling is everything.

p.s. I don't want to be rude or angry, this is just my observations on rust community. In any case, I removed assume_init. let's use more cpu cycles, lets heat the world :)
